### ISSUE TITLE
Reproducing the results of Simpo and dpo 

### ISSUE THREAD

**Issue by lucasliunju** [sail-sg/oat#10]
Hi,

Thanks for your great work.

I try to reproduce the results of offline dpo and offline simpo and I found the reproduced resltus are better the results in the paper. For example, for the results in the Figure 5 about dpo. I find the reproduced results about dpo is 76, which is better than the results in the paper (about 70). For the reproduced results of offline simpo, it illustrates a similar phenomenon, the reproduced result is 79, which is higher than the results in the readme of this repo. I would like to ask whether this is a normal phenomenon. 

Thank you in advance!

Lucas

**Comment by lkevinzc** [comment]
Hi Lucas @lucasliunju,

Thank you for your interest!

May I know which preference oracle did you use? All results in the paper are based on the setting where `Skywork-Reward-Llama-3.1-8B` is used as the preference oracle, while in the README I used `llm-blender/PairRM` to show a more lighweight example for quick experimentation.

Switching from `llm-blender/PairRM` to `Skywork-Reward-Llama-3.1-8B` is necessary when we apply strong online alignment algorithms, because they are more likely to exploit the preference oracle (and may lead to "oracle hacking"). Note that an ideal preference oracle should be a population, but we use strong reward models (or using GPT-as-a-judge in Section 6.4) to simulate it for the sake of accessibility.

Please also find reproduced curves at wandb: https://wandb.ai/lkevinzc/oat-llm (under the filter "reward_oracle:remote"), where you can see the learning curves closely follow those in the paper.

Best regards,
Zichen

**Comment by lkevinzc** [comment]
If it is A100-80G, I think it is possible to just run it with 2 A100: Run
```bash
MOSEC_LOG_LEVEL=debug python -m oat.oracles.remote.server --cuda-devices 0,1
```
Then refer to the script here: https://github.com/sail-sg/oat/tree/main/examples#locally-hosted-mosec-service to add the preference oracle and the url, but still use the script in the README (https://github.com/sail-sg/oat?tab=readme-ov-file#usage) to set 2 gpus and collocation.

If it's A100-40G, I am not sure. You may try and see if it will OOM.

**Comment by lkevinzc** [comment]
Hi @lucasliunju , this is because the remote server is a long-running process, it will not exit so the experiment will never run. In this case, you may try submitting the following script:
```diff
# 1. Start the oracle server.
# `&` runs the server in the background.
python -m oat.oracles.remote.server --cuda-devices 0 &

# 2. Loop until the server is ready (it needs time to load the model and warm up the GPUs).
- PROGRAM="bash /home/aiops/liuzc/oat/k8s/readiness.sh"
while true; do
    echo "Checking remote server..."
    
    # Run the program and check its exit status
    $PROGRAM
    STATUS=$?

    if [ $STATUS -eq 0 ]; then
        echo "Server ready!"
        break
    else
        echo "Keep waiting..."
        sleep 10
    fi
done

# 3. Ready to run the experiment.
echo "Starting the experiment..."
python -m oat.experiment.main \
    --gpus 2 \
    --collocate \
    --dap-algo SimPO \
    --beta 2 \
    --preference-oracle remote \
    --remote-rm-url http://0.0.0.0:8000 \
    --pretrain trl-lib/pythia-1b-deduped-tldr-sft \
    --prompt-data lkevinzc/tldr-with-sft-reference \
    --output_key pythia-1b-reference \
    --sync-params-every 1 \
    --rollout-batch-size-per-device 64 \
    --pi-buffer-maxlen-per-device 64 \
    --train-batch-size-per-device 8 \
    --use-wb \
    --wb-run-name 1b_pairrm_simpo_online

# 4. Clean up.
echo "Stopping the server..."
pkill -f python
```
Remember to change the directory to your oat project path (as highlighted). Hope this helps!

**Comment by lkevinzc** [comment]
This is due to a breaking change on the argument name... Please update to the latest `oat` package: `pip install -U oat-llm` and try again.
